language: ruby
rvm:
  - 2.4
before_script:
  - gem install awesome_bot
  - jekyll build --config _config.yml,_config_prod.yml
script:
  - awesome_bot www/index.html --allow-redirect -w agilion.com,brighterlink.io,dubber.net,therealreal.com,marketfactory.com
