# Site settings
name: Elixir Companies
description: A curated list of companies using Elixir in production, organized by industry.
maintainers:
  - doomspork
  - burden

plugins:
  - jekyll-assets
  - kramdown
  - uglifier

collections:
  industries:
    output: true
    permalink: /industry/:title/
  companies:
    output: false
    #permalink: /company/:title/

defaults:
  - scope:
      path: ""
      type: industries
    values:
      layout: industry

# Social settings
github: doomspork/elixir-companies

# Build settings
source: src
destination: www
markdown: kramdown

compress_html:
  ignore:
    envs: ["development"]
  clippings: all
  comments: all
  endings: all
  startings: all
  blanklines: false
  profile: false

compression: true
gzip: true

exclude: ['config.ru', 'CONTRIBUTING.md', 'Gemfile', 'Gemfile.lock', 'Procfile', 'Rakefile', 'README.md']
assets:
  sources:
  - _assets/vendor
  digest: true
  compress:
    css: true
    js: uglifier
